// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Retrieves the default Firebase options for the current platform.
  ///
  /// Throws an [UnsupportedError] if the platform is not supported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ753MLJz_U5WhkMzHQJiOflrfI9c_jqE',
    appId: '1:869752552275:android:2fb68a2412db18c98c3fa6',
    messagingSenderId: '869752552275',
    projectId: 'libretexts-adapt',
    storageBucket: 'libretexts-adapt.appspot.com',
  );

  /// Firebase options for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIdiWdpbY2gDf27O06NW_6brpD9sQOfE',
    appId: '1:869752552275:ios:8ecd3e1b990c338c8c3fa6',
    messagingSenderId: '869752552275',
    projectId: 'libretexts-adapt',
    storageBucket: 'libretexts-adapt.appspot.com',
    iosClientId:
        '869752552275-0h1p0l0jospngggj57ha6fv2j8p4lldk.apps.googleusercontent.com',
    iosBundleId: 'edu.ualr.adapt.clicker',
  );
}
